function delta = sim_delta(in1,in2,in3)
%SIM_DELTA
%    DELTA = SIM_DELTA(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    12-May-2021 09:42:59

M = in3(1,:);
dr = in2(1,:);
dtheta = in2(2,:);
g = in3(3,:);
m = in3(2,:);
r = in1(1,:);
theta = in1(2,:);
delta = [M.*g-dtheta.^2.*m.*r-g.*m.*cos(theta);dr.*dtheta.*m.*r.*2.0+g.*m.*r.*sin(theta)];
